### PR TITLE
fix link parenthesis issue

### LINKED ISSUE #12: issues with links in brackets
typing a link in brackets is not working, eg. sth. as `A great chat app (see https://delta.chat/en/)`

unfortunately, this is contradictory to https://github.com/deltachat/deltachat-desktop/issues/2238

example ...

A great chat app (see https://delta.chat/en/) vs. https://en.wikipedia.org/wiki/Bracket_(disambiguation) 

... markdown on github does it right, also ios (did not test android yet). technically, the second link is wrong afaik, however, in practise we cannot insist on that, these links just exist in masses :)

another bug i found during testing ...

a great chat app (see https://delta.chat) is not linkified at all.

### PR DESCRIPTION
**Pull request by Simon-Laux**
- add tests for #12
- allow other brackets in path part: `{`,`}`,`[`,`]`,`<`,`>`
- count the parentheses in links closes #12
- fix the second part of the issue #12 which I forgot to fix in the last commit: starting a bracket at the end of a link: `https://delta.chat/page(this is the link to our site)` (when it is not closed in the link its not taken)

### CODE REVIEW

File: src/parser/parse_from_text/text_elements.rs [hunk 1]
```diff
@@ -66,15 +67,97 @@ fn not_link_part_char(c: char) -> bool {
...
+            '[' => {
+                brackets_count += 1;
+                // if there is no closing bracket in the link, then don't take the bracket as a part of the link
+                if (<&str>::clone(&consumed)).slice(i..).find(']').is_none() {
+                    alternative_offset = Some(i);
+                    break;
+                }
+            }
+            '<' => {
+                angle_backets += 1;
```
Comment (Jikstra) [inline src/parser/parse_from_text/text_elements.rs:106]: Typo, var name should bei `angle_brackets`

**Review by Jikstra — APPROVED** [review]
